[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
singularity_council = "4k7JhCHjs2uoiP1hmvYDawnwJuXMt5ZhUJotvMRqedKS"
singularity_registry = "7CxZRBgnYwi5MtSKebmaSh7XTRVXk3QgzjXRUgLzcXT5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:anchor"
